# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_creditcarddetail_orderpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcarddetail',
            name='orderpayment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creditcard', to='shop.OrderPayment'),
        ),
    ]
